version: "3.9"
services:

  db:
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_DATABASE}
    ports:
      - "5432:5432"
    volumes:
      - ./init_db/:/docker-entrypoint-initdb.d/
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 5s

  main:
    build:
      context: .
    depends_on:
      db:
        condition: service_healthy
    links:
      - "db"
    environment:
      - P2P_NODE_HOST=${P2P_NODE_HOST}
      - P2P_NODE_PORT=${P2P_NODE_PORT}
      - PORT=${PORT}
      - API_PORT=${API_PORT}
      - DEBUG=${DEBUG}
      - PROTOCOL=${PROTOCOL}
    ports:
      - "14132:14132"
      - "${P2P_NODE_PORT}:${P2P_NODE_PORT}"
      - "${PORT}:${PORT}"
      - "${API_PORT}:${API_PORT}"
